#!/usr/bin/env python3
"""
IPDL to Rust translator

This script translates IPDL (Inter-Process communication Definition Language) 
files to Rust code, reusing Firefox's IPDL parser.
"""

import sys
import os
import argparse
from pathlib import Path

# Add Firefox IPDL directory to Python path
FIREFOX_IPDL_DIR = Path(__file__).parent / "firefox" / "ipc" / "ipdl"
sys.path.insert(0, str(FIREFOX_IPDL_DIR))

# Import IPDL modules
import ipdl.parser
import ipdl.ast
from ipdl.util import hash_str


class RustCodeGenerator:
    """Generates Rust code from IPDL AST"""
    
    def __init__(self):
        self.indent_level = 0
        self.output = []
        
    def indent(self):
        """Return current indentation string"""
        return "    " * self.indent_level
        
    def emit(self, code):
        """Emit a line of code with proper indentation"""
        if code:
            self.output.append(self.indent() + code)
        else:
            self.output.append("")
            
    def emit_raw(self, code):
        """Emit code without indentation"""
        self.output.append(code)
        
    def get_output(self):
        """Get the generated code as a string"""
        return "\n".join(self.output)
        
    def generate(self, tu):
        """Generate Rust code from a TranslationUnit"""
        # File header
        self.emit("// Automatically generated by ipdl2rust")
        self.emit("// DO NOT EDIT")
        self.emit("")
        
        # Generate code based on what's in the translation unit
        if tu.protocol:
            self.generate_protocol(tu)
        
        # Generate structs and unions
        for su in tu.structsAndUnions:
            if isinstance(su, ipdl.ast.StructDecl):
                self.generate_struct(su)
            elif isinstance(su, ipdl.ast.UnionDecl):
                self.generate_union(su)
                
        return self.get_output()
        
    def generate_protocol(self, tu):
        """Generate Rust code for a protocol"""
        protocol = tu.protocol
        
        # Use statements
        self.emit("use std::sync::Arc;")
        self.emit("use tokio::sync::mpsc;")
        self.emit("use serde::{Serialize, Deserialize};")
        self.emit("")
        
        # Generate message enums
        self.generate_message_enums(protocol)
        
        # Generate protocol trait
        self.generate_protocol_trait(protocol)
        
        # Generate parent and child implementations
        self.generate_parent_impl(protocol)
        self.generate_child_impl(protocol)
        
    def generate_message_enums(self, protocol):
        """Generate message enum types"""
        parent_messages = []
        child_messages = []
        
        for msg in protocol.messageDecls:
            if msg.direction == ipdl.ast.IN:  # Parent receives
                parent_messages.append(msg)
            else:  # Child receives
                child_messages.append(msg)
        
        # Generate parent message enum
        if parent_messages:
            self.emit("#[derive(Debug, Clone, Serialize, Deserialize)]")
            self.emit(f"pub enum {protocol.name}ParentMessage {{")
            self.indent_level += 1
            
            for msg in parent_messages:
                params = self.format_params(msg.inParams)
                if msg.sendSemantics == ipdl.ast.SYNC and msg.outParams:
                    # Sync messages need a response channel
                    self.emit(f"{msg.name}{params},")
                else:
                    self.emit(f"{msg.name}{params},")
                    
            self.indent_level -= 1
            self.emit("}")
            self.emit("")
        
        # Generate child message enum
        if child_messages:
            self.emit("#[derive(Debug, Clone, Serialize, Deserialize)]")
            self.emit(f"pub enum {protocol.name}ChildMessage {{")
            self.indent_level += 1
            
            for msg in child_messages:
                params = self.format_params(msg.inParams)
                self.emit(f"{msg.name}{params},")
                    
            self.indent_level -= 1
            self.emit("}")
            self.emit("")
            
        # Generate response types for sync messages
        for msg in protocol.messageDecls:
            if msg.sendSemantics == ipdl.ast.SYNC and msg.outParams:
                self.emit("#[derive(Debug, Clone, Serialize, Deserialize)]")
                self.emit(f"pub struct {msg.name}Response {{")
                self.indent_level += 1
                
                for param in msg.outParams:
                    rust_type = self.ipdl_type_to_rust(param.type)
                    self.emit(f"pub {param.name}: {rust_type},")
                    
                self.indent_level -= 1
                self.emit("}")
                self.emit("")
    
    def format_params(self, params):
        """Format parameters for enum variant or function"""
        if not params:
            return ""
            
        if len(params) == 1:
            return f"({self.ipdl_type_to_rust(params[0].type)})"
        else:
            # Named fields for multiple parameters
            fields = []
            for param in params:
                rust_type = self.ipdl_type_to_rust(param.type)
                fields.append(f"{param.name}: {rust_type}")
            return " { " + ", ".join(fields) + " }"
    
    def generate_protocol_trait(self, protocol):
        """Generate the protocol trait"""
        self.emit(f"pub trait {protocol.name}Protocol {{")
        self.indent_level += 1
        
        # Generate methods for each message the protocol can receive
        for msg in protocol.messageDecls:
            if msg.direction == ipdl.ast.IN:  # Parent receives
                self.generate_trait_method(msg, "parent")
            else:  # Child receives  
                self.generate_trait_method(msg, "child")
                
        self.indent_level -= 1
        self.emit("}")
        self.emit("")
        
    def generate_trait_method(self, msg, side):
        """Generate a trait method for a message"""
        # Method name
        method_name = f"handle_{self.to_snake_case(msg.name)}"
        
        # Parameters
        params = ["&mut self"]
        for param in msg.inParams:
            rust_type = self.ipdl_type_to_rust(param.type)
            params.append(f"{param.name}: {rust_type}")
            
        # Return type
        if msg.sendSemantics == ipdl.ast.SYNC and msg.outParams:
            returns = []
            for param in msg.outParams:
                rust_type = self.ipdl_type_to_rust(param.type)
                returns.append(rust_type)
            
            if len(returns) == 1:
                return_type = f" -> Result<{returns[0]}, Box<dyn std::error::Error>>"
            else:
                return_type = f" -> Result<({', '.join(returns)}), Box<dyn std::error::Error>>"
        else:
            return_type = " -> Result<(), Box<dyn std::error::Error>>"
            
        # Emit method signature
        self.emit(f"async fn {method_name}({', '.join(params)}){return_type};")
        
    def generate_parent_impl(self, protocol):
        """Generate parent actor implementation"""
        self.emit(f"pub struct {protocol.name}Parent {{")
        self.indent_level += 1
        self.emit("// Add fields as needed")
        self.indent_level -= 1
        self.emit("}")
        self.emit("")
        
        self.emit(f"impl {protocol.name}Parent {{")
        self.indent_level += 1
        self.emit("pub fn new() -> Self {")
        self.indent_level += 1
        self.emit("Self {}")
        self.indent_level -= 1
        self.emit("}")
        self.indent_level -= 1
        self.emit("}")
        self.emit("")
        
    def generate_child_impl(self, protocol):
        """Generate child actor implementation"""
        self.emit(f"pub struct {protocol.name}Child {{")
        self.indent_level += 1
        self.emit("// Add fields as needed")
        self.indent_level -= 1
        self.emit("}")
        self.emit("")
        
        self.emit(f"impl {protocol.name}Child {{")
        self.indent_level += 1
        self.emit("pub fn new() -> Self {")
        self.indent_level += 1
        self.emit("Self {}")
        self.indent_level -= 1
        self.emit("}")
        self.indent_level -= 1
        self.emit("}")
        self.emit("")
        
    def generate_struct(self, struct):
        """Generate a Rust struct from StructDecl"""
        self.emit("#[derive(Debug, Clone, Serialize, Deserialize)]")
        self.emit(f"pub struct {struct.name} {{")
        self.indent_level += 1
        
        for field in struct.fields:
            rust_type = self.ipdl_type_to_rust(field.typespec)
            self.emit(f"pub {field.name}: {rust_type},")
            
        self.indent_level -= 1
        self.emit("}")
        self.emit("")
        
    def generate_union(self, union):
        """Generate a Rust enum from UnionDecl"""
        self.emit("#[derive(Debug, Clone, Serialize, Deserialize)]")
        self.emit(f"pub enum {union.name} {{")
        self.indent_level += 1
        
        for i, component in enumerate(union.components):
            rust_type = self.ipdl_type_to_rust(component)
            # Generate variant names based on type
            variant_name = self.type_to_variant_name(component)
            self.emit(f"{variant_name}({rust_type}),")
            
        self.indent_level -= 1
        self.emit("}")
        self.emit("")
        
    def ipdl_type_to_rust(self, typespec):
        """Convert IPDL type to Rust type"""
        if isinstance(typespec, ipdl.ast.BuiltinType):
            type_map = {
                "bool": "bool",
                "int8_t": "i8",
                "uint8_t": "u8",
                "int16_t": "i16",
                "uint16_t": "u16",
                "int32_t": "i32",
                "uint32_t": "u32",
                "int64_t": "i64",
                "uint64_t": "u64",
                "float": "f32",
                "double": "f64",
                "nsString": "String",
                "nsCString": "String",
                "nsAString": "String",
                "nsACString": "String",
                "nsDependentSubstring": "String",
                "nsDependentCSubstring": "String",
            }
            return type_map.get(typespec.name, typespec.name)
        elif isinstance(typespec, ipdl.ast.ImportedType):
            # Handle imported types
            return typespec.name
        elif isinstance(typespec, ipdl.ast.ArrayType):
            inner = self.ipdl_type_to_rust(typespec.basetype)
            return f"Vec<{inner}>"
        elif isinstance(typespec, ipdl.ast.MaybeType):
            inner = self.ipdl_type_to_rust(typespec.basetype)
            return f"Option<{inner}>"
        elif hasattr(typespec, 'name'):
            return typespec.name
        else:
            # Default fallback
            return "Vec<u8>"  # Binary data
            
    def type_to_variant_name(self, typespec):
        """Generate enum variant name from type"""
        if hasattr(typespec, 'name'):
            return typespec.name.replace("::", "")
        return "Variant"
        
    def to_snake_case(self, name):
        """Convert CamelCase to snake_case"""
        import re
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
        return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def main():
    parser = argparse.ArgumentParser(description='Translate IPDL to Rust')
    parser.add_argument('input', help='Input IPDL file')
    parser.add_argument('-o', '--output', help='Output Rust file (default: stdout)')
    parser.add_argument('--include', action='append', default=[],
                       help='Include directories for IPDL files')
    
    args = parser.parse_args()
    
    # Set up include paths
    include_dirs = [str(FIREFOX_IPDL_DIR)]
    include_dirs.extend(args.include)
    
    # Parse the IPDL file
    with open(args.input, 'r') as f:
        content = f.read()
        
    # Create parser
    parser = ipdl.parser.Parser()
    
    # Parse the file
    try:
        tu = parser.parse(content, args.input, includedirs=include_dirs)
    except Exception as e:
        print(f"Error parsing IPDL file: {e}", file=sys.stderr)
        return 1
        
    # Generate Rust code
    generator = RustCodeGenerator()
    rust_code = generator.generate(tu)
    
    # Output the code
    if args.output:
        with open(args.output, 'w') as f:
            f.write(rust_code)
    else:
        print(rust_code)
        
    return 0


if __name__ == "__main__":
    sys.exit(main())