#!/usr/bin/env python3
"""
Standalone IPDL to Rust translator

This script translates IPDL files to Rust code without requiring
the full Firefox build environment.
"""

import sys
import re
import argparse
from pathlib import Path
from dataclasses import dataclass
from typing import List, Optional, Union


# AST node classes
@dataclass
class Param:
    name: str
    type: str
    
@dataclass
class Message:
    name: str
    is_sync: bool
    direction: str  # "parent" or "child"
    in_params: List[Param]
    out_params: List[Param]
    
@dataclass
class Protocol:
    name: str
    namespace: Optional[str]
    messages: List[Message]


class IPDLParser:
    """Simple IPDL parser"""
    
    def parse(self, content: str) -> Protocol:
        lines = content.strip().split('\n')
        
        protocol_name = None
        namespace = None
        messages = []
        current_direction = None
        
        i = 0
        while i < len(lines):
            line = lines[i].strip()
            
            # Skip empty lines and comments
            if not line or line.startswith('//'):
                i += 1
                continue
                
            # Parse namespace
            if line.startswith('namespace'):
                match = re.match(r'namespace\s+(\w+)\s*{', line)
                if match:
                    namespace = match.group(1)
                    
            # Parse protocol declaration
            elif line.startswith('protocol'):
                match = re.match(r'protocol\s+(\w+)\s*{', line)
                if match:
                    protocol_name = match.group(1)
                    
            # Parse direction
            elif line.endswith(':'):
                current_direction = line[:-1]
                
            # Parse message
            elif line.startswith(('async', 'sync')):
                msg = self.parse_message(line, current_direction)
                if msg:
                    messages.append(msg)
                    
            i += 1
            
        return Protocol(protocol_name, namespace, messages)
        
    def parse_message(self, line: str, direction: str) -> Optional[Message]:
        """Parse a message declaration"""
        # Match async/sync message pattern
        match = re.match(r'(async|sync)\s+(\w+)\s*\((.*?)\)(\s+returns\s*\((.*?)\))?\s*;', line)
        if not match:
            return None
            
        is_sync = match.group(1) == 'sync'
        name = match.group(2)
        in_params_str = match.group(3)
        out_params_str = match.group(5) if match.group(5) else ""
        
        in_params = self.parse_params(in_params_str)
        out_params = self.parse_params(out_params_str) if out_params_str else []
        
        return Message(name, is_sync, direction, in_params, out_params)
        
    def parse_params(self, params_str: str) -> List[Param]:
        """Parse parameter list"""
        params = []
        if not params_str.strip():
            return params
            
        # Simple parameter parsing
        parts = params_str.split(',')
        for part in parts:
            part = part.strip()
            if part:
                # Split type and name
                tokens = part.split()
                if len(tokens) >= 2:
                    type_name = ' '.join(tokens[:-1])
                    param_name = tokens[-1]
                    params.append(Param(param_name, type_name))
                    
        return params


class RustGenerator:
    """Generate Rust code from parsed IPDL"""
    
    def __init__(self):
        self.indent = 0
        self.output = []
        
    def emit(self, line: str = ""):
        """Emit a line with proper indentation"""
        if line:
            self.output.append("    " * self.indent + line)
        else:
            self.output.append("")
            
    def generate(self, protocol: Protocol) -> str:
        """Generate Rust code for a protocol"""
        # Header
        self.emit("// Automatically generated by ipdl2rust_standalone")
        self.emit("// DO NOT EDIT")
        self.emit()
        
        # Imports
        self.emit("use serde::{Serialize, Deserialize};")
        self.emit("use std::error::Error;")
        self.emit()
        
        # Namespace module
        if protocol.namespace:
            self.emit(f"pub mod {protocol.namespace} {{")
            self.indent += 1
            
        # Generate message enums
        self.generate_message_enums(protocol)
        
        # Generate protocol trait
        self.generate_trait(protocol)
        
        # Generate actor structs
        self.generate_actors(protocol)
        
        if protocol.namespace:
            self.indent -= 1
            self.emit("}")
            
        return '\n'.join(self.output)
        
    def generate_message_enums(self, protocol: Protocol):
        """Generate message enum types"""
        parent_msgs = [m for m in protocol.messages if m.direction == "parent"]
        child_msgs = [m for m in protocol.messages if m.direction == "child"]
        
        # Parent messages enum
        if parent_msgs:
            self.emit("#[derive(Debug, Clone, Serialize, Deserialize)]")
            self.emit(f"pub enum {protocol.name}ParentMessage {{")
            self.indent += 1
            
            for msg in parent_msgs:
                if msg.in_params:
                    fields = self.format_enum_fields(msg.in_params)
                    self.emit(f"{msg.name} {fields},")
                else:
                    self.emit(f"{msg.name},")
                    
            self.indent -= 1
            self.emit("}")
            self.emit()
            
        # Child messages enum
        if child_msgs:
            self.emit("#[derive(Debug, Clone, Serialize, Deserialize)]")
            self.emit(f"pub enum {protocol.name}ChildMessage {{")
            self.indent += 1
            
            for msg in child_msgs:
                if msg.in_params:
                    fields = self.format_enum_fields(msg.in_params)
                    self.emit(f"{msg.name} {fields},")
                else:
                    self.emit(f"{msg.name},")
                    
            self.indent -= 1
            self.emit("}")
            self.emit()
            
        # Response types for sync messages
        for msg in protocol.messages:
            if msg.is_sync and msg.out_params:
                self.emit("#[derive(Debug, Clone, Serialize, Deserialize)]")
                self.emit(f"pub struct {msg.name}Response {{")
                self.indent += 1
                
                for param in msg.out_params:
                    rust_type = self.ipdl_to_rust_type(param.type)
                    self.emit(f"pub {param.name}: {rust_type},")
                    
                self.indent -= 1
                self.emit("}")
                self.emit()
                
    def format_enum_fields(self, params: List[Param]) -> str:
        """Format fields for enum variant"""
        if len(params) == 1:
            rust_type = self.ipdl_to_rust_type(params[0].type)
            return f"({rust_type})"
        else:
            fields = []
            for param in params:
                rust_type = self.ipdl_to_rust_type(param.type)
                fields.append(f"{param.name}: {rust_type}")
            return "{ " + ", ".join(fields) + " }"
            
    def generate_trait(self, protocol: Protocol):
        """Generate protocol trait"""
        self.emit(f"pub trait {protocol.name}Protocol {{")
        self.indent += 1
        
        for msg in protocol.messages:
            self.generate_trait_method(msg)
            
        self.indent -= 1
        self.emit("}")
        self.emit()
        
    def generate_trait_method(self, msg: Message):
        """Generate a trait method for a message"""
        method_name = f"handle_{self.to_snake_case(msg.name)}"
        
        # Build parameter list
        params = ["&mut self"]
        for param in msg.in_params:
            rust_type = self.ipdl_to_rust_type(param.type)
            params.append(f"{param.name}: {rust_type}")
            
        # Build return type
        if msg.is_sync and msg.out_params:
            if len(msg.out_params) == 1:
                return_type = self.ipdl_to_rust_type(msg.out_params[0].type)
                return_str = f" -> Result<{return_type}, Box<dyn Error>>"
            else:
                types = [self.ipdl_to_rust_type(p.type) for p in msg.out_params]
                return_str = f" -> Result<({', '.join(types)}), Box<dyn Error>>"
        else:
            return_str = " -> Result<(), Box<dyn Error>>"
            
        self.emit(f"async fn {method_name}({', '.join(params)}){return_str};")
        
    def generate_actors(self, protocol: Protocol):
        """Generate parent and child actor structs"""
        # Parent actor
        self.emit(f"pub struct {protocol.name}Parent {{")
        self.indent += 1
        self.emit("// Add protocol-specific fields here")
        self.indent -= 1
        self.emit("}")
        self.emit()
        
        self.emit(f"impl {protocol.name}Parent {{")
        self.indent += 1
        self.emit("pub fn new() -> Self {")
        self.indent += 1
        self.emit("Self {}")
        self.indent -= 1
        self.emit("}")
        self.indent -= 1
        self.emit("}")
        self.emit()
        
        # Child actor
        self.emit(f"pub struct {protocol.name}Child {{")
        self.indent += 1
        self.emit("// Add protocol-specific fields here")
        self.indent -= 1
        self.emit("}")
        self.emit()
        
        self.emit(f"impl {protocol.name}Child {{")
        self.indent += 1
        self.emit("pub fn new() -> Self {")
        self.indent += 1
        self.emit("Self {}")
        self.indent -= 1
        self.emit("}")
        self.indent -= 1
        self.emit("}")
        
    def ipdl_to_rust_type(self, ipdl_type: str) -> str:
        """Convert IPDL type to Rust type"""
        type_map = {
            "bool": "bool",
            "int8_t": "i8",
            "uint8_t": "u8",
            "int16_t": "i16", 
            "uint16_t": "u16",
            "int32_t": "i32",
            "uint32_t": "u32",
            "int64_t": "i64",
            "uint64_t": "u64",
            "float": "f32",
            "double": "f64",
            "nsString": "String",
            "nsCString": "String",
            "nsAString": "String",
            "nsACString": "String",
        }
        
        return type_map.get(ipdl_type, ipdl_type)
        
    def to_snake_case(self, name: str) -> str:
        """Convert CamelCase to snake_case"""
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
        return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def main():
    parser = argparse.ArgumentParser(description='Translate IPDL to Rust')
    parser.add_argument('input', help='Input IPDL file')
    parser.add_argument('-o', '--output', help='Output Rust file (default: stdout)')
    
    args = parser.parse_args()
    
    # Read input file
    with open(args.input, 'r') as f:
        content = f.read()
        
    # Parse IPDL
    ipdl_parser = IPDLParser()
    protocol = ipdl_parser.parse(content)
    
    # Generate Rust code
    generator = RustGenerator()
    rust_code = generator.generate(protocol)
    
    # Output
    if args.output:
        with open(args.output, 'w') as f:
            f.write(rust_code)
        print(f"Generated {args.output}")
    else:
        print(rust_code)
        

if __name__ == "__main__":
    main()