// Automatically generated by ipdl2rust_standalone
// DO NOT EDIT

use serde::{Serialize, Deserialize};
use std::error::Error;

pub mod test {
    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub enum TestProtocolParentMessage {
        Hello (String),
        GetValue (i32),
        UpdateData { id: i32, data: String },
    }

    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub enum TestProtocolChildMessage {
        Welcome (String),
        DataChanged { id: i32, newValue: String },
    }

    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct GetValueResponse {
        pub value: String,
    }

    pub trait TestProtocolProtocol {
        async fn handle_hello(&mut self, message: String) -> Result<(), Box<dyn Error>>;
        async fn handle_get_value(&mut self, id: i32) -> Result<String, Box<dyn Error>>;
        async fn handle_update_data(&mut self, id: i32, data: String) -> Result<(), Box<dyn Error>>;
        async fn handle_welcome(&mut self, greeting: String) -> Result<(), Box<dyn Error>>;
        async fn handle_data_changed(&mut self, id: i32, newValue: String) -> Result<(), Box<dyn Error>>;
    }

    pub struct TestProtocolParent {
        // Add protocol-specific fields here
    }

    impl TestProtocolParent {
        pub fn new() -> Self {
            Self {}
        }
    }

    pub struct TestProtocolChild {
        // Add protocol-specific fields here
    }

    impl TestProtocolChild {
        pub fn new() -> Self {
            Self {}
        }
    }
}