// Generated by CoffeeScript 2.7.0
var desugar;

desugar = function({
    rules: sugared,
    ...rest
  }) {
  var choices, flatten;
  return {
    ...rest,
    supertypes: function($) {
      var collect;
      return Array.from((collect = function*(rules) {
        var key, results, value;
        results = [];
        for (key in rules) {
          value = rules[key];
          if (!(typeof value === 'object')) {
            continue;
          }
          yield* collect(value);
          results.push((yield $[key]));
        }
        return results;
      })(sugared));
    },
    rules: Object.assign(Object.fromEntries((flatten = function*(rules) {
      var key, results, value;
      results = [];
      for (key in rules) {
        value = rules[key];
        if (typeof value === 'object') {
          results.push((yield* flatten(value)));
        } else {
          results.push((yield [key, value]));
        }
      }
      return results;
    })(sugared)), Object.fromEntries((choices = function*(rules) {
      var key, results, value;
      results = [];
      for (key in rules) {
        value = rules[key];
        if (!(typeof value === 'object')) {
          continue;
        }
        yield* choices(value);
        results.push((yield [
          key,
          (function(value) { // Copy value in the returned lambda
            return function($) {
              var subtype;
              return choice(...((function() {
                var i,
          len,
          ref,
          results1;
                ref = Object.keys(value);
                results1 = [];
                for (i = 0, len = ref.length; i < len; i++) {
                  subtype = ref[i];
                  results1.push($[subtype]);
                }
                return results1;
              })()));
            };
          })(value)
        ]));
      }
      return results;
    })(sugared)))
  };
};

export default grammar(desugar({
  name: 'zine',
  extras: function($) {
    return [];
  },
  word: function($) {
    return $.identifier;
  },
  rules: {
    text: function($) {
      return repeat1($.token);
    },
    token: {
      span: function($) {
        return seq(token(seq(field('keyword', /[a-z]+/), '{')), $.text, '}');
      },
      word: function($) {
        return /[^ \r\n{}]+/;
      },
      math: {
        display: function($) {
          return seq('{{', $.expression, '}}');
        },
        inline: function($) {
          return seq('{', $.expression, '}');
        }
      }
    },
    _expression: function($) {
      return choice(prec.left(1, seq(' ', $._expression)), $.expression);
    },
    expression: {
      identifier: function($) {
        return /[a-zA-Z]+/;
      },
      integer: function($) {
        return /[0-9]+/;
      },
      noncommutative: function($) {
        return choice(prec.left(2, seq($._expression, ' ', $._expression)), prec.left(seq($.parens, $.parens)));
      },
      commutative: function($) {
        return prec.left(3, seq($.expression, field('operator', choice(' + ', ' - ')), choice($.expression, $.ellipsis)));
      },
      set: function($) {
        return seq('[', $.expression, '|', $.expression, ']');
      },
      bra: function($) {
        return seq('<', $.expression, '|');
      },
      ket: function($) {
        return seq('|', $.expression, '>');
      },
      projection: function($) {
        return prec(1, seq('<', $.expression, '|', $.expression, '>'));
      },
      interval: function($) {
        return seq(field('start', choice('(', '[')), $.expression, ',', $.expression, field('end', choice(')', ']')));
      },
      parens: function($) {
        return seq('(', $.expression, ')');
      }
    },
    ellipsis: function($) {
      return '...';
    }
  }
}));

// binary: ($) -> prec.left seq $.expression, $.binop, choice $.expression, '...'
// binop: ($) -> choice(
// 	' + '
// 	'/'
// )
// exists: ($) -> seq 'E', $.expression, '. ', $.expression
// forall: ($) -> seq 'A', $.expression, '. ', $.expression
// postfix: ($) -> seq $.root, /['!#]/
// integer: ($) -> /[0-9]+/
// subscript: ($) -> prec.left 2, seq $.root, '_', $.expression
// superscript: ($) -> prec.left 2, seq $.root, '^', $.expression
// choice(
// 	prec.left 3, seq $.expression, ' ', $.expression
// 	prec.left 1, seq $.root, $.parens
// 	prec.left 3, seq $.parens, $.parens
// )
// division: ($) -> prec.left seq $.root, '/', $.root
// binop: -> choice(
// '+'
// '-'
// '/'
// '='
// '*'
// '<'
// '>'
// '==>'
// '<=='
// '<=>'
// '<='
// '>='
// ':='
// 'and'
// 'or'
// 'in'
// 'contains'
// )
// negation: ($) -> prec.left 4, seq '-', $.root
// not: ($) -> prec.left 4, seq 'not', '\s+', $.root
