// Generated by CoffeeScript 2.7.0
import {
  desugar,
  unthisify
} from './sugar.js';

// TODO double-check precedence
export default grammar(desugar(unthisify({
  name: 'zine',
  extras: function() { // Whitespace-sensitive language
    return [];
  },
  word: function() {
    return this.identifier;
  },
  rules: {
    text: function() {
      return seq(this.token, repeat(seq(' ', this.token)));
    },
    punctuation: function() {
      return /[.!?:;,]/;
    },
    token: {
      span: function() {
        return seq(field('keyword', /[a-z]+\{/), this.text, '}');
      },
      word: function() {
        return /[^ \r\n{}]+/;
      },
      math: {
        display: function() {
          return seq('{{', this.expression, '}}');
        },
        inline: function() {
          return seq('{', this.expression, '}');
        }
      }
    },
    _expression: function() {
      return choice(prec.left(2, seq(' ', this._expression)), this.expression);
    },
    expression: {
      atom: {
        identifier: function() {
          return /[a-zA-Z]+/;
        },
        integer: function() {
          return /[0-9]+/;
        },
        script: {
          superscript: function() {
            return prec.right(seq(choice(this.atom, this.parens, this.norm), '^', choice(this.atom, this.parens, this.negation)));
          },
          subscript: function() {
            return prec.right(seq(choice(this.atom, this.norm), '_', choice(this.atom, this.parens, this.negation)));
          }
        },
        postfix: function() {
          return seq(this.atom, field('operator', /[!#']/));
        }
      },
      negation: function() {
        return prec(2, seq('-', choice(this.atom, this.parens)));
      },
      noncommutative: function() {
        return choice(prec.left(3, seq(this._expression, ' ', this._expression)), prec.left(seq(this.parens, this.parens)));
      },
      commutative: function() {
        return prec.left(1, seq(this._expression, field('operator', choice(' + ', ' - ')), choice(this._expression, this.ellipsis)));
      },
      norm: function() {
        return seq('|', this.expression, '|');
      },
      set: function() {
        return seq('[', choice(this.elements, seq(this.expression, '|', this.expression)), ']');
      },
      bra: function() {
        return seq('<', this.expression, '|');
      },
      ket: function() {
        return seq('|', this.expression, '>');
      },
      projection: function() {
        return prec(1, seq('<', this.expression, '|', this.expression, '>'));
      },
      interval: function() {
        return seq(field('start', choice('(', '[')), this.expression, '..', this.expression, field('end', choice(')', ']')));
      },
      parens: function() {
        return seq('(', this.expression, ')');
      }
    },
    elements: function() {
      return seq(this.expression, ',', this.expression, repeat(seq(',', this.expression)), optional(seq(',', this.ellipsis, optional(seq(',', this.expression, repeat(seq(',', this.expression)))))));
    },
    ellipsis: function() {
      return '...';
    }
  }
})));
