// Generated by CoffeeScript 2.7.0
export var desugar = function({
    rules: sugared,
    ...rest
  }) {
  var choices, flatten;
  return {
    ...rest,
    supertypes: function($) {
      var collect;
      return Array.from((collect = function*(rules) {
        var key, results, value;
        results = [];
        for (key in rules) {
          value = rules[key];
          if (!(typeof value === 'object')) {
            continue;
          }
          yield* collect(value);
          results.push((yield $[key]));
        }
        return results;
      })(sugared));
    },
    rules: Object.assign(Object.fromEntries((flatten = function*(rules) {
      var key, results, value;
      results = [];
      for (key in rules) {
        value = rules[key];
        if (typeof value === 'object') {
          results.push((yield* flatten(value)));
        } else {
          results.push((yield [key, value]));
        }
      }
      return results;
    })(sugared)), Object.fromEntries((choices = function*(rules) {
      var key, results, value;
      results = [];
      for (key in rules) {
        value = rules[key];
        if (!(typeof value === 'object')) {
          continue;
        }
        yield* choices(value);
        results.push((yield [
          key,
          (function(value) { // Copy value in the returned lambda
            return function($) {
              var subtype;
              return choice(...((function() {
                var i,
          len,
          ref,
          results1;
                ref = Object.keys(value);
                results1 = [];
                for (i = 0, len = ref.length; i < len; i++) {
                  subtype = ref[i];
                  results1.push($[subtype]);
                }
                return results1;
              })()));
            };
          })(value)
        ]));
      }
      return results;
    })(sugared)))
  };
};

export var unthisify = function(obj) {
  var key, value;
  for (key in obj) {
    value = obj[key];
    if (typeof value === 'function') {
      obj[key] = (function(value) {
        return function($) {
          return value.bind($)();
        };
      })(value);
    } else if (typeof value === 'object') {
      unthisify(value);
    }
  }
  return obj;
};
