name: zine
version: 0.1.0.0
build-type: Custom
custom-setup:
  dependencies:
    - base
    - Cabal
    - process
dependencies:
  - base
  - hs-conllu
  - typst
  - yi-core
  - inline-c-cpp
  - pretty-simple
executable:
  main: Zine.lhs
  default-extensions:
    - BlockArguments
    - ConstraintKinds
    - DataKinds
    - DeriveFunctor
    - GADTs
    - KindSignatures
    - PolyKinds
    - QuasiQuotes
    - TemplateHaskell
    - TypeFamilies
    - UnicodeSyntax
  include-dirs:
    - udpipe/src_lib_only
  ghc-options:
    - -fobject-code
