name: zine
version: 0.1.0.0
dependencies: base
executable:
  main: Zine.lhs
  default-extensions:
    - DeriveFunctor
    - ConstraintKinds
    - KindSignatures
    - TypeFamilies
    - UnicodeSyntax
