/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 15
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_DOLLAR = 2,
  sym_ellipsis = 3,
  sym_integer = 4,
  anon_sym_SPACE = 5,
  anon_sym_PLUS = 6,
  anon_sym_DASH = 7,
  anon_sym_LBRACE = 8,
  anon_sym_PIPE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_LT = 11,
  anon_sym_GT = 12,
  anon_sym_LPAREN = 13,
  anon_sym_LBRACK = 14,
  anon_sym_COMMA = 15,
  anon_sym_RPAREN = 16,
  anon_sym_RBRACK = 17,
  sym_inline = 18,
  sym__expression = 19,
  sym__unspaced = 20,
  sym__spacer = 21,
  sym_noncommutative = 22,
  sym_commutative = 23,
  sym_set = 24,
  sym_bra = 25,
  sym_ket = 26,
  sym_projection = 27,
  sym_interval = 28,
  sym_parens = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_DOLLAR] = "$",
  [sym_ellipsis] = "ellipsis",
  [sym_integer] = "integer",
  [anon_sym_SPACE] = " ",
  [anon_sym_PLUS] = " + ",
  [anon_sym_DASH] = " - ",
  [anon_sym_LBRACE] = "{",
  [anon_sym_PIPE] = "|",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LPAREN] = "(",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_RBRACK] = "]",
  [sym_inline] = "inline",
  [sym__expression] = "_expression",
  [sym__unspaced] = "_unspaced",
  [sym__spacer] = "_spacer",
  [sym_noncommutative] = "noncommutative",
  [sym_commutative] = "commutative",
  [sym_set] = "set",
  [sym_bra] = "bra",
  [sym_ket] = "ket",
  [sym_projection] = "projection",
  [sym_interval] = "interval",
  [sym_parens] = "parens",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_ellipsis] = sym_ellipsis,
  [sym_integer] = sym_integer,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_inline] = sym_inline,
  [sym__expression] = sym__expression,
  [sym__unspaced] = sym__unspaced,
  [sym__spacer] = sym__spacer,
  [sym_noncommutative] = sym_noncommutative,
  [sym_commutative] = sym_commutative,
  [sym_set] = sym_set,
  [sym_bra] = sym_bra,
  [sym_ket] = sym_ket,
  [sym_projection] = sym_projection,
  [sym_interval] = sym_interval,
  [sym_parens] = sym_parens,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_ellipsis] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_inline] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__unspaced] = {
    .visible = false,
    .named = true,
  },
  [sym__spacer] = {
    .visible = false,
    .named = true,
  },
  [sym_noncommutative] = {
    .visible = true,
    .named = true,
  },
  [sym_commutative] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_bra] = {
    .visible = true,
    .named = true,
  },
  [sym_ket] = {
    .visible = true,
    .named = true,
  },
  [sym_projection] = {
    .visible = true,
    .named = true,
  },
  [sym_interval] = {
    .visible = true,
    .named = true,
  },
  [sym_parens] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_end = 1,
  field_operator = 2,
  field_start = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_end] = "end",
  [field_operator] = "operator",
  [field_start] = "start",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operator, 1},
  [1] =
    {field_end, 4},
    {field_start, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        ' ', 10,
        '$', 6,
        '(', 18,
        ')', 21,
        ',', 20,
        '.', 4,
        '<', 16,
        '>', 17,
        '[', 19,
        ']', 22,
        '{', 13,
        '|', 14,
        '}', 15,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(3);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_ellipsis);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '+') ADVANCE(1);
      if (lookahead == '-') ADVANCE(2);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_ellipsis] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_inline] = STATE(39),
    [anon_sym_DOLLAR] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__expression] = STATE(37),
    [sym__unspaced] = STATE(29),
    [sym__spacer] = STATE(37),
    [sym_noncommutative] = STATE(29),
    [sym_commutative] = STATE(29),
    [sym_set] = STATE(29),
    [sym_bra] = STATE(29),
    [sym_ket] = STATE(29),
    [sym_projection] = STATE(29),
    [sym_interval] = STATE(29),
    [sym_parens] = STATE(15),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_DOLLAR] = ACTIONS(7),
    [sym_integer] = ACTIONS(5),
    [anon_sym_SPACE] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(7),
    [anon_sym_RBRACK] = ACTIONS(7),
  },
  [STATE(3)] = {
    [sym__expression] = STATE(37),
    [sym__unspaced] = STATE(22),
    [sym__spacer] = STATE(37),
    [sym_noncommutative] = STATE(22),
    [sym_commutative] = STATE(22),
    [sym_set] = STATE(22),
    [sym_bra] = STATE(22),
    [sym_ket] = STATE(22),
    [sym_projection] = STATE(22),
    [sym_interval] = STATE(22),
    [sym_parens] = STATE(15),
    [sym_identifier] = ACTIONS(21),
    [sym_ellipsis] = ACTIONS(23),
    [sym_integer] = ACTIONS(21),
    [anon_sym_SPACE] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(4)] = {
    [sym__expression] = STATE(36),
    [sym__unspaced] = STATE(18),
    [sym__spacer] = STATE(36),
    [sym_noncommutative] = STATE(18),
    [sym_commutative] = STATE(18),
    [sym_set] = STATE(18),
    [sym_bra] = STATE(18),
    [sym_ket] = STATE(18),
    [sym_projection] = STATE(18),
    [sym_interval] = STATE(18),
    [sym_parens] = STATE(15),
    [sym_identifier] = ACTIONS(27),
    [sym_integer] = ACTIONS(27),
    [anon_sym_SPACE] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(5)] = {
    [sym__expression] = STATE(17),
    [sym__unspaced] = STATE(18),
    [sym__spacer] = STATE(17),
    [sym_noncommutative] = STATE(18),
    [sym_commutative] = STATE(18),
    [sym_set] = STATE(18),
    [sym_bra] = STATE(18),
    [sym_ket] = STATE(18),
    [sym_projection] = STATE(18),
    [sym_interval] = STATE(18),
    [sym_parens] = STATE(15),
    [sym_identifier] = ACTIONS(27),
    [sym_integer] = ACTIONS(27),
    [anon_sym_SPACE] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(6)] = {
    [sym__expression] = STATE(37),
    [sym__unspaced] = STATE(31),
    [sym__spacer] = STATE(37),
    [sym_noncommutative] = STATE(31),
    [sym_commutative] = STATE(31),
    [sym_set] = STATE(31),
    [sym_bra] = STATE(31),
    [sym_ket] = STATE(31),
    [sym_projection] = STATE(31),
    [sym_interval] = STATE(31),
    [sym_parens] = STATE(15),
    [sym_identifier] = ACTIONS(29),
    [sym_integer] = ACTIONS(29),
    [anon_sym_SPACE] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(7)] = {
    [sym__expression] = STATE(37),
    [sym__unspaced] = STATE(32),
    [sym__spacer] = STATE(37),
    [sym_noncommutative] = STATE(32),
    [sym_commutative] = STATE(32),
    [sym_set] = STATE(32),
    [sym_bra] = STATE(32),
    [sym_ket] = STATE(32),
    [sym_projection] = STATE(32),
    [sym_interval] = STATE(32),
    [sym_parens] = STATE(15),
    [sym_identifier] = ACTIONS(31),
    [sym_integer] = ACTIONS(31),
    [anon_sym_SPACE] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(8)] = {
    [sym__expression] = STATE(37),
    [sym__unspaced] = STATE(33),
    [sym__spacer] = STATE(37),
    [sym_noncommutative] = STATE(33),
    [sym_commutative] = STATE(33),
    [sym_set] = STATE(33),
    [sym_bra] = STATE(33),
    [sym_ket] = STATE(33),
    [sym_projection] = STATE(33),
    [sym_interval] = STATE(33),
    [sym_parens] = STATE(15),
    [sym_identifier] = ACTIONS(33),
    [sym_integer] = ACTIONS(33),
    [anon_sym_SPACE] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(9)] = {
    [sym__expression] = STATE(37),
    [sym__unspaced] = STATE(27),
    [sym__spacer] = STATE(37),
    [sym_noncommutative] = STATE(27),
    [sym_commutative] = STATE(27),
    [sym_set] = STATE(27),
    [sym_bra] = STATE(27),
    [sym_ket] = STATE(27),
    [sym_projection] = STATE(27),
    [sym_interval] = STATE(27),
    [sym_parens] = STATE(15),
    [sym_identifier] = ACTIONS(35),
    [sym_integer] = ACTIONS(35),
    [anon_sym_SPACE] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(10)] = {
    [sym__expression] = STATE(37),
    [sym__unspaced] = STATE(35),
    [sym__spacer] = STATE(37),
    [sym_noncommutative] = STATE(35),
    [sym_commutative] = STATE(35),
    [sym_set] = STATE(35),
    [sym_bra] = STATE(35),
    [sym_ket] = STATE(35),
    [sym_projection] = STATE(35),
    [sym_interval] = STATE(35),
    [sym_parens] = STATE(15),
    [sym_identifier] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [anon_sym_SPACE] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(11)] = {
    [sym__expression] = STATE(20),
    [sym__unspaced] = STATE(18),
    [sym__spacer] = STATE(20),
    [sym_noncommutative] = STATE(18),
    [sym_commutative] = STATE(18),
    [sym_set] = STATE(18),
    [sym_bra] = STATE(18),
    [sym_ket] = STATE(18),
    [sym_projection] = STATE(18),
    [sym_interval] = STATE(18),
    [sym_parens] = STATE(15),
    [sym_identifier] = ACTIONS(27),
    [sym_integer] = ACTIONS(27),
    [anon_sym_SPACE] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(12)] = {
    [sym__expression] = STATE(37),
    [sym__unspaced] = STATE(34),
    [sym__spacer] = STATE(37),
    [sym_noncommutative] = STATE(34),
    [sym_commutative] = STATE(34),
    [sym_set] = STATE(34),
    [sym_bra] = STATE(34),
    [sym_ket] = STATE(34),
    [sym_projection] = STATE(34),
    [sym_interval] = STATE(34),
    [sym_parens] = STATE(15),
    [sym_identifier] = ACTIONS(39),
    [sym_integer] = ACTIONS(39),
    [anon_sym_SPACE] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(13)] = {
    [sym__expression] = STATE(37),
    [sym__unspaced] = STATE(30),
    [sym__spacer] = STATE(37),
    [sym_noncommutative] = STATE(30),
    [sym_commutative] = STATE(30),
    [sym_set] = STATE(30),
    [sym_bra] = STATE(30),
    [sym_ket] = STATE(30),
    [sym_projection] = STATE(30),
    [sym_interval] = STATE(30),
    [sym_parens] = STATE(15),
    [sym_identifier] = ACTIONS(41),
    [sym_integer] = ACTIONS(41),
    [anon_sym_SPACE] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
  [STATE(14)] = {
    [sym__expression] = STATE(37),
    [sym__unspaced] = STATE(28),
    [sym__spacer] = STATE(37),
    [sym_noncommutative] = STATE(28),
    [sym_commutative] = STATE(28),
    [sym_set] = STATE(28),
    [sym_bra] = STATE(28),
    [sym_ket] = STATE(28),
    [sym_projection] = STATE(28),
    [sym_interval] = STATE(28),
    [sym_parens] = STATE(15),
    [sym_identifier] = ACTIONS(43),
    [sym_integer] = ACTIONS(43),
    [anon_sym_SPACE] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(47), 1,
      anon_sym_SPACE,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    STATE(23), 1,
      sym_parens,
    ACTIONS(45), 9,
      anon_sym_DOLLAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [21] = 2,
    ACTIONS(53), 1,
      anon_sym_SPACE,
    ACTIONS(51), 10,
      anon_sym_DOLLAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [37] = 2,
    ACTIONS(57), 1,
      anon_sym_SPACE,
    ACTIONS(55), 9,
      anon_sym_DOLLAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [52] = 3,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(59), 7,
      anon_sym_DOLLAR,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [69] = 2,
    ACTIONS(67), 1,
      anon_sym_SPACE,
    ACTIONS(65), 9,
      anon_sym_DOLLAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [84] = 2,
    ACTIONS(71), 1,
      anon_sym_SPACE,
    ACTIONS(69), 9,
      anon_sym_DOLLAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [99] = 2,
    ACTIONS(75), 1,
      anon_sym_SPACE,
    ACTIONS(73), 9,
      anon_sym_DOLLAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [114] = 2,
    ACTIONS(75), 1,
      anon_sym_SPACE,
    ACTIONS(73), 9,
      anon_sym_DOLLAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [129] = 2,
    ACTIONS(79), 1,
      anon_sym_SPACE,
    ACTIONS(77), 9,
      anon_sym_DOLLAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [144] = 2,
    ACTIONS(83), 1,
      anon_sym_SPACE,
    ACTIONS(81), 9,
      anon_sym_DOLLAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [159] = 2,
    ACTIONS(87), 1,
      anon_sym_SPACE,
    ACTIONS(85), 9,
      anon_sym_DOLLAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [174] = 2,
    ACTIONS(91), 1,
      anon_sym_SPACE,
    ACTIONS(89), 9,
      anon_sym_DOLLAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [189] = 4,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(93), 1,
      anon_sym_COMMA,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [203] = 3,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(97), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [215] = 3,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(99), 1,
      anon_sym_GT,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [226] = 3,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [237] = 3,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(101), 1,
      anon_sym_PIPE,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [248] = 3,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(103), 1,
      anon_sym_GT,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [259] = 3,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(105), 1,
      anon_sym_PIPE,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [270] = 3,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [281] = 3,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(93), 1,
      anon_sym_COMMA,
    ACTIONS(63), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [292] = 2,
    ACTIONS(109), 1,
      anon_sym_DOLLAR,
    ACTIONS(111), 1,
      anon_sym_SPACE,
  [299] = 1,
    ACTIONS(111), 1,
      anon_sym_SPACE,
  [303] = 1,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
  [307] = 1,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(15)] = 0,
  [SMALL_STATE(16)] = 21,
  [SMALL_STATE(17)] = 37,
  [SMALL_STATE(18)] = 52,
  [SMALL_STATE(19)] = 69,
  [SMALL_STATE(20)] = 84,
  [SMALL_STATE(21)] = 99,
  [SMALL_STATE(22)] = 114,
  [SMALL_STATE(23)] = 129,
  [SMALL_STATE(24)] = 144,
  [SMALL_STATE(25)] = 159,
  [SMALL_STATE(26)] = 174,
  [SMALL_STATE(27)] = 189,
  [SMALL_STATE(28)] = 203,
  [SMALL_STATE(29)] = 215,
  [SMALL_STATE(30)] = 226,
  [SMALL_STATE(31)] = 237,
  [SMALL_STATE(32)] = 248,
  [SMALL_STATE(33)] = 259,
  [SMALL_STATE(34)] = 270,
  [SMALL_STATE(35)] = 281,
  [SMALL_STATE(36)] = 292,
  [SMALL_STATE(37)] = 299,
  [SMALL_STATE(38)] = 303,
  [SMALL_STATE(39)] = 307,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bra, 3, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__unspaced, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__unspaced, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parens, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parens, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__spacer, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ket, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ket, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_noncommutative, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_noncommutative, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commutative, 3, 0, 1),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commutative, 3, 0, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_noncommutative, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_noncommutative, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 5, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 5, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_projection, 5, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_projection, 5, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interval, 5, 0, 2),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interval, 5, 0, 2),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zine(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "zine",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
