/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 34
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_SPACE = 2,
  sym_integer = 3,
  anon_sym_LBRACE = 4,
  anon_sym_PIPE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_LT = 7,
  anon_sym_GT = 8,
  anon_sym_LPAREN = 9,
  anon_sym_LBRACK = 10,
  anon_sym_COMMA = 11,
  anon_sym_RPAREN = 12,
  anon_sym_RBRACK = 13,
  sym_source = 14,
  sym__expression = 15,
  sym__spacer = 16,
  sym__unspaced = 17,
  sym_multiplication = 18,
  sym_set = 19,
  sym_bra = 20,
  sym_ket = 21,
  sym_projection = 22,
  sym_interval = 23,
  sym_parens = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SPACE] = " ",
  [sym_integer] = "integer",
  [anon_sym_LBRACE] = "{",
  [anon_sym_PIPE] = "|",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LPAREN] = "(",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_RBRACK] = "]",
  [sym_source] = "source",
  [sym__expression] = "_expression",
  [sym__spacer] = "_spacer",
  [sym__unspaced] = "_unspaced",
  [sym_multiplication] = "multiplication",
  [sym_set] = "set",
  [sym_bra] = "bra",
  [sym_ket] = "ket",
  [sym_projection] = "projection",
  [sym_interval] = "interval",
  [sym_parens] = "parens",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [sym_integer] = sym_integer,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source] = sym_source,
  [sym__expression] = sym__expression,
  [sym__spacer] = sym__spacer,
  [sym__unspaced] = sym__unspaced,
  [sym_multiplication] = sym_multiplication,
  [sym_set] = sym_set,
  [sym_bra] = sym_bra,
  [sym_ket] = sym_ket,
  [sym_projection] = sym_projection,
  [sym_interval] = sym_interval,
  [sym_parens] = sym_parens,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__spacer] = {
    .visible = false,
    .named = true,
  },
  [sym__unspaced] = {
    .visible = false,
    .named = true,
  },
  [sym_multiplication] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_bra] = {
    .visible = true,
    .named = true,
  },
  [sym_ket] = {
    .visible = true,
    .named = true,
  },
  [sym_projection] = {
    .visible = true,
    .named = true,
  },
  [sym_interval] = {
    .visible = true,
    .named = true,
  },
  [sym_parens] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_end = 1,
  field_start = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_end] = "end",
  [field_start] = "start",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_end, 4},
    {field_start, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      ADVANCE_MAP(
        ' ', 2,
        '(', 10,
        ')', 13,
        ',', 12,
        '<', 8,
        '>', 9,
        '[', 11,
        ']', 14,
        '{', 5,
        '|', 6,
        '}', 7,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(32),
    [sym__expression] = STATE(25),
    [sym__spacer] = STATE(25),
    [sym__unspaced] = STATE(25),
    [sym_multiplication] = STATE(25),
    [sym_set] = STATE(25),
    [sym_bra] = STATE(25),
    [sym_ket] = STATE(25),
    [sym_projection] = STATE(25),
    [sym_interval] = STATE(25),
    [sym_parens] = STATE(13),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_SPACE] = ACTIONS(5),
    [sym_integer] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym__expression] = STATE(33),
    [sym__spacer] = STATE(33),
    [sym__unspaced] = STATE(29),
    [sym_multiplication] = STATE(29),
    [sym_set] = STATE(29),
    [sym_bra] = STATE(29),
    [sym_ket] = STATE(29),
    [sym_projection] = STATE(29),
    [sym_interval] = STATE(29),
    [sym_parens] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_SPACE] = ACTIONS(5),
    [sym_integer] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_GT] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym__expression] = STATE(15),
    [sym__spacer] = STATE(15),
    [sym__unspaced] = STATE(15),
    [sym_multiplication] = STATE(15),
    [sym_set] = STATE(15),
    [sym_bra] = STATE(15),
    [sym_ket] = STATE(15),
    [sym_projection] = STATE(15),
    [sym_interval] = STATE(15),
    [sym_parens] = STATE(13),
    [sym_identifier] = ACTIONS(21),
    [anon_sym_SPACE] = ACTIONS(5),
    [sym_integer] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [STATE(4)] = {
    [sym__expression] = STATE(33),
    [sym__spacer] = STATE(33),
    [sym__unspaced] = STATE(26),
    [sym_multiplication] = STATE(26),
    [sym_set] = STATE(26),
    [sym_bra] = STATE(26),
    [sym_ket] = STATE(26),
    [sym_projection] = STATE(26),
    [sym_interval] = STATE(26),
    [sym_parens] = STATE(13),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_SPACE] = ACTIONS(5),
    [sym_integer] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [STATE(5)] = {
    [sym__expression] = STATE(33),
    [sym__spacer] = STATE(33),
    [sym__unspaced] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_set] = STATE(30),
    [sym_bra] = STATE(30),
    [sym_ket] = STATE(30),
    [sym_projection] = STATE(30),
    [sym_interval] = STATE(30),
    [sym_parens] = STATE(13),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_SPACE] = ACTIONS(5),
    [sym_integer] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [STATE(6)] = {
    [sym__expression] = STATE(33),
    [sym__spacer] = STATE(33),
    [sym__unspaced] = STATE(31),
    [sym_multiplication] = STATE(31),
    [sym_set] = STATE(31),
    [sym_bra] = STATE(31),
    [sym_ket] = STATE(31),
    [sym_projection] = STATE(31),
    [sym_interval] = STATE(31),
    [sym_parens] = STATE(13),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_SPACE] = ACTIONS(5),
    [sym_integer] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [STATE(7)] = {
    [sym__expression] = STATE(33),
    [sym__spacer] = STATE(33),
    [sym__unspaced] = STATE(22),
    [sym_multiplication] = STATE(22),
    [sym_set] = STATE(22),
    [sym_bra] = STATE(22),
    [sym_ket] = STATE(22),
    [sym_projection] = STATE(22),
    [sym_interval] = STATE(22),
    [sym_parens] = STATE(13),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_SPACE] = ACTIONS(5),
    [sym_integer] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [STATE(8)] = {
    [sym__expression] = STATE(33),
    [sym__spacer] = STATE(33),
    [sym__unspaced] = STATE(24),
    [sym_multiplication] = STATE(24),
    [sym_set] = STATE(24),
    [sym_bra] = STATE(24),
    [sym_ket] = STATE(24),
    [sym_projection] = STATE(24),
    [sym_interval] = STATE(24),
    [sym_parens] = STATE(13),
    [sym_identifier] = ACTIONS(31),
    [anon_sym_SPACE] = ACTIONS(5),
    [sym_integer] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [STATE(9)] = {
    [sym__expression] = STATE(18),
    [sym__spacer] = STATE(18),
    [sym__unspaced] = STATE(18),
    [sym_multiplication] = STATE(18),
    [sym_set] = STATE(18),
    [sym_bra] = STATE(18),
    [sym_ket] = STATE(18),
    [sym_projection] = STATE(18),
    [sym_interval] = STATE(18),
    [sym_parens] = STATE(13),
    [sym_identifier] = ACTIONS(33),
    [anon_sym_SPACE] = ACTIONS(5),
    [sym_integer] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [STATE(10)] = {
    [sym__expression] = STATE(33),
    [sym__spacer] = STATE(33),
    [sym__unspaced] = STATE(28),
    [sym_multiplication] = STATE(28),
    [sym_set] = STATE(28),
    [sym_bra] = STATE(28),
    [sym_ket] = STATE(28),
    [sym_projection] = STATE(28),
    [sym_interval] = STATE(28),
    [sym_parens] = STATE(13),
    [sym_identifier] = ACTIONS(35),
    [anon_sym_SPACE] = ACTIONS(5),
    [sym_integer] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [STATE(11)] = {
    [sym__expression] = STATE(33),
    [sym__spacer] = STATE(33),
    [sym__unspaced] = STATE(27),
    [sym_multiplication] = STATE(27),
    [sym_set] = STATE(27),
    [sym_bra] = STATE(27),
    [sym_ket] = STATE(27),
    [sym_projection] = STATE(27),
    [sym_interval] = STATE(27),
    [sym_parens] = STATE(13),
    [sym_identifier] = ACTIONS(37),
    [anon_sym_SPACE] = ACTIONS(5),
    [sym_integer] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [STATE(12)] = {
    [sym__expression] = STATE(33),
    [sym__spacer] = STATE(33),
    [sym__unspaced] = STATE(23),
    [sym_multiplication] = STATE(23),
    [sym_set] = STATE(23),
    [sym_bra] = STATE(23),
    [sym_ket] = STATE(23),
    [sym_projection] = STATE(23),
    [sym_interval] = STATE(23),
    [sym_parens] = STATE(13),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_SPACE] = ACTIONS(5),
    [sym_integer] = ACTIONS(39),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    STATE(16), 1,
      sym_parens,
    ACTIONS(41), 8,
      ts_builtin_sym_end,
      anon_sym_SPACE,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [17] = 1,
    ACTIONS(45), 9,
      ts_builtin_sym_end,
      anon_sym_SPACE,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [29] = 2,
    ACTIONS(49), 1,
      anon_sym_SPACE,
    ACTIONS(47), 7,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [42] = 1,
    ACTIONS(51), 8,
      ts_builtin_sym_end,
      anon_sym_SPACE,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [53] = 1,
    ACTIONS(53), 8,
      ts_builtin_sym_end,
      anon_sym_SPACE,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [64] = 1,
    ACTIONS(55), 8,
      ts_builtin_sym_end,
      anon_sym_SPACE,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [75] = 1,
    ACTIONS(57), 8,
      ts_builtin_sym_end,
      anon_sym_SPACE,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [86] = 1,
    ACTIONS(59), 8,
      ts_builtin_sym_end,
      anon_sym_SPACE,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [97] = 1,
    ACTIONS(61), 8,
      ts_builtin_sym_end,
      anon_sym_SPACE,
      anon_sym_PIPE,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [108] = 3,
    ACTIONS(63), 1,
      anon_sym_SPACE,
    ACTIONS(65), 1,
      anon_sym_COMMA,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
  [118] = 2,
    ACTIONS(63), 1,
      anon_sym_SPACE,
    ACTIONS(69), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [126] = 2,
    ACTIONS(63), 1,
      anon_sym_SPACE,
    ACTIONS(65), 1,
      anon_sym_COMMA,
  [133] = 2,
    ACTIONS(49), 1,
      anon_sym_SPACE,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
  [140] = 2,
    ACTIONS(63), 1,
      anon_sym_SPACE,
    ACTIONS(73), 1,
      anon_sym_PIPE,
  [147] = 2,
    ACTIONS(63), 1,
      anon_sym_SPACE,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
  [154] = 2,
    ACTIONS(63), 1,
      anon_sym_SPACE,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
  [161] = 2,
    ACTIONS(63), 1,
      anon_sym_SPACE,
    ACTIONS(77), 1,
      anon_sym_GT,
  [168] = 2,
    ACTIONS(63), 1,
      anon_sym_SPACE,
    ACTIONS(79), 1,
      anon_sym_GT,
  [175] = 2,
    ACTIONS(63), 1,
      anon_sym_SPACE,
    ACTIONS(81), 1,
      anon_sym_PIPE,
  [182] = 1,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
  [186] = 1,
    ACTIONS(49), 1,
      anon_sym_SPACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 17,
  [SMALL_STATE(15)] = 29,
  [SMALL_STATE(16)] = 42,
  [SMALL_STATE(17)] = 53,
  [SMALL_STATE(18)] = 64,
  [SMALL_STATE(19)] = 75,
  [SMALL_STATE(20)] = 86,
  [SMALL_STATE(21)] = 97,
  [SMALL_STATE(22)] = 108,
  [SMALL_STATE(23)] = 118,
  [SMALL_STATE(24)] = 126,
  [SMALL_STATE(25)] = 133,
  [SMALL_STATE(26)] = 140,
  [SMALL_STATE(27)] = 147,
  [SMALL_STATE(28)] = 154,
  [SMALL_STATE(29)] = 161,
  [SMALL_STATE(30)] = 168,
  [SMALL_STATE(31)] = 175,
  [SMALL_STATE(32)] = 182,
  [SMALL_STATE(33)] = 186,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bra, 3, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__unspaced, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parens, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__spacer, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplication, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ket, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplication, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 5, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_projection, 5, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interval, 5, 0, 1),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [83] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zine(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "zine",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
