name:                yine
dependencies:
  - base >=4.8 && <5
  - yi-core
  - yi-language
  - yi-dynamic-configuration
  - yi-keymap-emacs
  - yi-frontend-vty
  - yi-mode-haskell
  - yi-mode-javascript
  - yi-misc-modes
  - yi-rope
  - oo-prototypes
  - microlens-platform
library:
  source-dirs: src
executables:
  yine:
    main: Main.hs
    source-dirs: app
    dependencies:
      - yine
    ghc-options:
      - -O2
      - -threaded
tests:
  yine-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - yine
      - hspec
      - base
      - exceptions
