#![allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code
)]
include!(concat!(env!("OUT_DIR"), "/ecl_bindings.rs")); // This is generated by bindgen in build.rs
